			****CREATE DATABASE****

CREATE DATABASE bank_loan_db;

		****CUSTOMER RELATION****

CREATE TABLE CUSTOMER(
CUSTOMER_ID SERIAL NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME 	VARCHAR(50) NOT NULL,
NIC 		VARCHAR(20) UNIQUE NOT NULL,
email		VARCHAR(100) UNIQUE NOT NULL,
PHONE		VARCHAR(40)	UNIQUE NOT NULL,
ADDRESS		TEXT NOT NULL,
CREATED_AT 	DATE DEFAULT CURRENT_TIMESTAMP NOT NULL

);

******************
ALTER TABLE CUSTOMER
MODIFY COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
******************

		****USERS RELATION****

CREATE TABLE USERS(
USERS_ID SERIAL NOT NULL,
USERNAME VARCHAR(100) UNIQUE NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
ROLE VARCHAR(20) NOT NULL,
CUSTOMER_ID INT NOT NULL,

CONSTRAINT PK_USERS PRIMARY KEY(USERS_ID),
CONSTRAINT FK_USERS_CUS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

		****LOAN APPLICATION RELATION****

CREATE TABLE LOAN_APPLICATION(

APPLICATION_ID SERIAL NOT NULL,
CUSTOMER_ID INT NOT NULL,
LOAN_TYPE VARCHAR(50) NOT NULL,
REQUESTED_AMOUNT DECIMAL(12,2) NOT NULL,
PURPOSE TEXT NOT NULL,
APPLICATION_DATE DATE DEFAULT CURRENT_DATE,
STATUS VARCHAR(20) NOT NULL,

CONSTRAINT PK_APP PRIMARY KEY (APPLICATION_ID),
CONSTRAINT FK_APP_CUS FOREIGN KEY CUSTOMER_ID REFERENCES CUSTOMER(CUSTOMER_ID)

);

		****LOAN RELATION****

CREATE TABLE LOAN(
LOAN_ID SERIAL PRIMARY KEY,
APPLICATION_ID INT UNIQUE,
APPROVED_AMOUNT DECIMAL(12,2) NOT NULL,
INTEREST_RATE DECIMAL(5,2) NOT NULL,
DURATION_MONTH INT NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
STATUS VARCHAR(20) NOT NULL,

CONSTRAINT FK_LN_APPID FOREIGN KEY(APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);

		****PAYMENT RELATION****

CREATE TABLE payment (
    payment_id SERIAL PRIMARY KEY NOT NULL,
    loanID INT NOT NULL ,
    payment_date DATE  NOT NULL DEFAULT CURRENT_DATE,
    amount DECIMAL(12,2) NOT NULL,
    payment_status VARCHAR(20) NOT NULL,

    CONSTRAINT FK_PY_LN FOREIGN KEY(loanID) REFERENCES LOAN(LOAN_ID)
);

		****STAFF RELATION****

CREATE TABLE staff(
    staff_id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(100),
    email VARCHAR(100),
    position VARCHAR(50)

);

		****APPLICATION REVIEW RELATION****

CREATE TABLE application_review (
    review_id SERIAL PRIMARY KEY,
    application_id INT,
    staff_id INT,
    decision VARCHAR(20),
    comments TEXT,
    review_date DATE DEFAULT CURRENT_DATE,

    FOREIGN KEY(application_id)
    REFERENCES loan_application(application_id),

    FOREIGN KEY(staff_id)
    REFERENCES staff(staff_id)

);
